update=čet 22 avg 2013 10:36:52 CEST
version=1
last_client=kicad
[eeschema]
version=1
LibDir=
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=special
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=/home/dean/Downloads/mchck-master/hardware/adafruit
LibName32=/home/dean/Downloads/mchck-master/hardware/cn3063
LibName33=/home/dean/Downloads/mchck-master/hardware/conn_15
LibName34=/home/dean/Downloads/mchck-master/hardware/conn_16
LibName35=/home/dean/Downloads/mchck-master/hardware/conn_18
LibName36=/home/dean/Downloads/mchck-master/hardware/inductor_select
LibName37=/home/dean/Downloads/mchck-master/hardware/logo
LibName38=/home/dean/Downloads/mchck-master/hardware/mchck-cache
LibName39=/home/dean/Downloads/mchck-master/hardware/mcp1702
LibName40=/home/dean/Downloads/mchck-master/hardware/mcp73831
LibName41=/home/dean/Downloads/mchck-master/hardware/mic5205
LibName42=/home/dean/Downloads/mchck-master/hardware/microsd
LibName43=/home/dean/Downloads/mchck-master/hardware/MK20LF
LibName44=/home/dean/Downloads/mchck-master/hardware/mounthole
LibName45=/home/dean/Downloads/mchck-master/hardware/multireg
LibName46=/home/dean/Downloads/mchck-master/hardware/nuc120ld
LibName47=/home/dean/Downloads/mchck-master/hardware/nuc120ldq48
LibName48=/home/dean/Downloads/mchck-master/hardware/NUC120_QFN48
LibName49=/home/dean/Downloads/mchck-master/hardware/SparkFun
LibName50=/home/dean/Downloads/mchck-master/hardware/STM32L15x_QFN48
LibName51=/home/dean/Downloads/mchck-master/hardware/tac_switchsmd_evqp2
LibName52=/home/dean/Downloads/mchck-master/hardware/vdda
LibName53=/home/dean/Downloads/mchck-master/hardware/vssa
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
version=1
LastNetListRead=breakout.net
UseCmpFile=1
PadDrill="    0,600000"
PadDrillOvalY="    0,600000"
PadSizeH="    1,000000"
PadSizeV="    1,000000"
PcbTextSizeV="    1,000000"
PcbTextSizeH="    1,000000"
PcbTextThickness="    0,300000"
ModuleTextSizeV="    1,000000"
ModuleTextSizeH="    1,000000"
ModuleTextSizeThickness="    0,150000"
SolderMaskClearance="    0,000000"
SolderMaskMinWidth="    0,000000"
DrawSegmentWidth="    0,200000"
BoardOutlineThickness="    0,150000"
ModuleOutlineThickness="    0,150000"
[pcbnew/libraries]
LibDir=
LibName1=/home/dean/Downloads/mchck-master/hardware/mchck
LibName2=sockets
LibName3=connect
LibName4=discret
LibName5=pin_array
LibName6=divers
LibName7=smd_capacitors
LibName8=smd_resistors
LibName9=smd_crystal&oscillator
LibName10=smd_dil
LibName11=smd_transistors
LibName12=libcms
LibName13=display
LibName14=led
LibName15=dip_sockets
LibName16=pga_sockets
LibName17=valves
[general]
version=1
